/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EButton: typeof import('./src/components/EButton.vue')['default']
    EDataDrivenForm: typeof import('./src/components/EDataDrivenForm.vue')['default']
    EInput: typeof import('./src/components/EInput.vue')['default']
    ETextfield: typeof import('./src/components/ETextfield.vue')['default']
    QBadge: typeof import('quasar')['QBadge']
    QCard: typeof import('quasar')['QCard']
    QForm: typeof import('quasar')['QForm']
    QLinearProgress: typeof import('quasar')['QLinearProgress']
  }
}
